# Fixing aioredis-py issue #778

There was a connection reset by peer error that appeared
in redis-py 4.0 and aioredis 2.0. This repository is
attempting to track down where this bug came from in 
redis-py and create a solution.

### License

Licensed under Apache 2.0

Written by [@Andrew-Chen-Wang](https://github.com/Andrew-Chen-Wang)
